apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-service
  namespace: rag-system
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fastapi-service
  template:
    metadata:
      labels:
        app: fastapi-service
    spec:
      containers:
      - name: fastapi-service
        image: your-registry/fastapi-service:latest
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1"
        ports:
        - containerPort: 8000
        env:
        - name: MODEL_SERVICE_URL
          value: "http://deepseek-model-service:8080"
        - name: CHROMA_HOST
          value: "chroma-service"
        envFrom:
        - secretRef:
            name: app-secrets