apiVersion: v1
kind: Service
metadata:
  name: deepseek-model-service
  namespace: rag-system
spec:
  selector:
    app: deepseek-model
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
  namespace: rag-system
spec:
  selector:
    app: fastapi-service
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: streamlit-ui-service
  namespace: rag-system
spec:
  selector:
    app: streamlit-ui
  ports:
    - protocol: TCP
      port: 8501
      targetPort: 8501
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: chroma-service
  namespace: rag-system
spec:
  selector:
    app: chroma-db
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP