apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: rag-system
type: Opaque
data:
  JWT_SECRET_KEY: ${JWT_SECRET_KEY_BASE64}
  MODEL_TEMPERATURE: ${MODEL_TEMPERATURE_BASE64}
  CHROMA_API_KEY: ${CHROMA_API_KEY_BASE64}
---
apiVersion: v1
kind: Secret
metadata:
  name: registry-credentials
  namespace: rag-system
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ${DOCKER_CONFIG_JSON_BASE64}
---
apiVersion: v1
kind: Secret
metadata:
  name: model-config
  namespace: rag-system
type: Opaque
data:
  config.json: ${MODEL_CONFIG_BASE64}