apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: rag-system
data:
  fluent.conf: |
    <source>
      @type tail
      path /var/log/containers/*.log
      pos_file /var/log/fluentd-containers.log.pos
      tag kubernetes.*
      read_from_head true
      <parse>
        @type json
        time_key time
        time_format %Y-%m-%dT%H:%M:%S.%NZ
      </parse>
    </source>

    <filter kubernetes.**>
      @type kubernetes_metadata
      kubernetes_url "#{ENV['KUBERNETES_URL']}"
      bearer_token_file /var/run/secrets/kubernetes.io/serviceaccount/token
      ca_file /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      skip_labels false
      skip_container_metadata false
    </filter>

    <match kubernetes.var.log.containers.**rag-system**.log>
      @type elasticsearch
      host elasticsearch-master
      port 9200
      logstash_format true
      logstash_prefix k8s-logs
      <buffer>
        @type file
        path /var/log/fluentd-buffers/kubernetes.system.buffer
        flush_mode interval
        retry_type exponential_backoff
        flush_thread_count 2
        flush_interval 5s
        retry_forever false
        retry_max_interval 30
        chunk_limit_size 2M
        queue_limit_length 8
        overflow_action block
      </buffer>
    </match>
---
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch
  namespace: rag-system
spec:
  version: 8.10.4
  nodeSets:
  - name: default
    count: 1
    config:
      node.store.allow_mmap: false
    podTemplate:
      spec:
        containers:
        - name: elasticsearch
          resources:
            requests:
              memory: 2Gi
              cpu: 0.5
            limits:
              memory: 4Gi
              cpu: 2
---
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana
  namespace: rag-system
spec:
  version: 8.10.4
  count: 1
  elasticsearchRef:
    name: elasticsearch
  podTemplate:
    spec:
      containers:
      - name: kibana
        resources:
          requests:
            memory: 512Mi
            cpu: 0.2
          limits:
            memory: 1Gi
            cpu: 1
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kibana-index-pattern
  namespace: rag-system
data:
  rag-system-pattern.json: |
    {
      "title": "rag-system-*",
      "timeFieldName": "@timestamp",
      "fields": [
        {"name": "kubernetes.container_name", "type": "string", "searchable": true},
        {"name": "kubernetes.namespace_name", "type": "string", "searchable": true},
        {"name": "log", "type": "string", "searchable": true},
        {"name": "stream", "type": "string", "searchable": true},
        {"name": "time", "type": "date", "searchable": true},
        {"name": "level", "type": "string", "searchable": true},
        {"name": "message", "type": "string", "searchable": true}
      ]
    }